# Generated by Django 2.0.dev20170217162938 on 2017-03-19 07:05

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='컨텐츠 내용', verbose_name='CONTENT'),
        ),
    ]
